In [21]:
import pandas as pd
import numpy as np

In [22]:
DATA_PATH = '/scratch/msc24h18/msc_project/results/test46/'
df1 = pd.read_csv(DATA_PATH + 'symmetric.csv')
df2 = pd.read_csv(DATA_PATH + 'asymmetric.csv')
df1.head()

,device_name,device_id,test_date,test_time,groundWGFMU,pulseWGFMU,startVolage1,endVoltage1,startVolage2,endVoltage2,...,granularity_up,granularity_down,epochs,test_acc,val_acc,val_loss,train_loss,pulses,pulses_pos,pulses_neg
0,LBE247,ID180XR1000Star,19.09.2024,16:28:56,SMU2,WGFMU1,0.0,2.5,0.0,-2.0,...,0.377899,0.150997,24.0,0.2807,0.279750,2.184394,2.185694,20451.0,10205.0,10246.0
1,LBE247,ID294YR,19.09.2024,11:05:17,SMU2,WGFMU1,0.0,4.0,0.0,-2.5,...,0.165229,0.122735,24.0,0.9642,0.964500,0.124142,0.086329,63508.0,36212.0,27296.0
2,LBE247,ID294YR,19.09.2024,11:21:56,SMU2,WGFMU1,0.0,3.0,0.0,-2.0,...,0.569685,0.244996,24.0,0.9605,0.953083,0.154754,0.124152,14843.0,9779.0,5064.0
3,LBE247,ID294YR,19.09.2024,11:13:50,SMU2,WGFMU1,0.0,3.0,0.0,-2.5,...,0.545234,0.112887,24.0,0.9580,0.955917,0.152095,0.122610,24432.0,16631.0,7801.0
4,LBE247,ID300XR1000Oct,19.09.2024,13:12:58,SMU2,WGFMU1,0.0,3.0,0.0,-2.0,...,0.306821,0.134838,24.0,0.2101,0.196083,2.219887,2.220648,612358.0,304185.0,308173.0

In [23]:
columns={'test_acc': 'test_acc_sym',
    'val_acc': 'val_acc_sym',
    'val_loss': 'val_loss_sym',
    'train_loss': 'train_loss_sym',
    'pulses': 'pulses_sym',
    'pulses_pos': 'pulses_pos_sym',
    'pulses_neg': 'pulses_neg_sym'
}

df1.rename(columns = columns, inplace = True)

for key in columns.keys():
    df1[key + '_asym'] = df2[key]

df1['granularity_diff'] = np.abs(df1['granularity_up'] - df1['granularity_down'])
df1['val_acc_diff'] = df1['val_acc_asym'] - df1['val_acc_sym']

In [24]:
df1.head()

,device_name,device_id,test_date,test_time,groundWGFMU,pulseWGFMU,startVolage1,endVoltage1,startVolage2,endVoltage2,...,pulses_neg_sym,test_acc_asym,val_acc_asym,val_loss_asym,train_loss_asym,pulses_asym,pulses_pos_asym,pulses_neg_asym,granularity_diff,val_acc_diff
0,LBE247,ID180XR1000Star,19.09.2024,16:28:56,SMU2,WGFMU1,0.0,2.5,0.0,-2.0,...,10246.0,0.8946,0.888500,0.403140,0.391618,28107.0,28107.0,0.0,0.226901,0.608750
1,LBE247,ID294YR,19.09.2024,11:05:17,SMU2,WGFMU1,0.0,4.0,0.0,-2.5,...,27296.0,0.9659,0.964917,0.122180,0.086599,60132.0,28118.0,32014.0,0.042493,0.000417
2,LBE247,ID294YR,19.09.2024,11:21:56,SMU2,WGFMU1,0.0,3.0,0.0,-2.0,...,5064.0,0.8908,0.883583,0.411509,0.401541,15080.0,15080.0,0.0,0.324689,-0.069500
3,LBE247,ID294YR,19.09.2024,11:13:50,SMU2,WGFMU1,0.0,3.0,0.0,-2.5,...,7801.0,0.8735,0.867417,0.470464,0.463579,22376.0,22376.0,0.0,0.432348,-0.088500
4,LBE247,ID300XR1000Oct,19.09.2024,13:12:58,SMU2,WGFMU1,0.0,3.0,0.0,-2.0,...,308173.0,0.8877,0.883000,0.418385,0.409925,40883.0,40883.0,0.0,0.171983,0.686917

In [25]:
df1.to_csv(DATA_PATH + 'combined.csv', index=False)